# --- Стадия сборки ---
FROM golang:1.24-bookworm AS build

WORKDIR /app

# Устанавливаем нужные зависимости (через apt, а не apk)
RUN apt-get update && apt-get install -y \
    git gcc g++ make librdkafka-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Копируем go.mod и go.sum и качаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь исходный код
COPY . .

# Сборка бинаря с включённым CGO (для Kafka)
RUN CGO_ENABLED=1 GOOS=linux go build -a -o agent .

# --- Финальная стадия ---
FROM alpine:latest

# Устанавливаем нужные библиотеки и инструменты
RUN apk --no-cache add ca-certificates curl docker-cli librdkafka

WORKDIR /root/

# Копируем бинарь из стадии сборки
COPY --from=build /app/agent .

EXPOSE 8080

ENTRYPOINT ["./agent"]
